### ISSUE TITLE
Environment variables are all undefined when next-plugin-preval is wrapped with `@sentry/nextjs` webpack plugin

### ISSUE THREAD

**Issue by Vadorequest** [ricokahler/next-plugin-preval#42]
PR: https://github.com/UnlyEd/next-right-now/pull/370/files

#### `http://localhost:8888/api/status`
![image](https://user-images.githubusercontent.com/3807458/121591784-31f53700-ca3a-11eb-8144-80a171f10833.png)

This is the expected behavior and that's what happens when not using `@sentry/nextjs` OR when using `withNextPluginPreval` as top-level wrapper.

`module.exports = withNextPluginPreval(withSentryConfig(...`

#### `http://localhost:8888/api/status`
![image](https://user-images.githubusercontent.com/3807458/121591984-708af180-ca3a-11eb-913a-0c220e71a388.png)

This is what happens when using `module.exports = withSentryConfig(withNextPluginPreval(...`

---

I'm not sure what's going wrong, but it drove me crazy for an hour.
Since `@sentry/nextjs` explicitly stated to wrap all webpack config, I assumed it would be safe and didn't notice the regression right away.

**Comment by ricokahler** [comment]
This _may_ be an upstream issue with `withSentryConfig`.

There are few different interfaces for this next config (e.g. in particular, it could take in a function, or take in an object). If the upstream plugin isn't handling all of those cases, it could result in something not propagating correctly. I'll take a look!

**Comment by ricokahler** [comment]
Looking at their latest source code, I can confirm that `@sentry/nextjs` is not handling the case when next.js config is a function.

https://github.com/getsentry/sentry-javascript/blob/62619534e524693f160663bb076a38edba475a19/packages/nextjs/src/utils/config.ts#L126-L129

compare that to `next-plugin-preval`:

https://github.com/ricokahler/next-plugin-preval/blob/f89525dfe8a1e01d5d450a9d610acbeeacf4e05b/src/create-next-plugin-preval.ts#L25-L28

this explains why it works when `withNextPluginPreval` is last and not vice versa. `next-plugin-preval` always returns a function since it accepts one.

**Comment by lobsterkatie** [comment]
Thanks for spotting that, @ricokahler. It's a known problem and is on our list to fix this sprint.
